title: RUNE
email: rune@runemadsen.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.runeform.com"
twitter_username: runeform
github_username:  runemadsen
author: Rune Madsen
author_twitter: runemadsen
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]
permalink: /:categories/:title
gems:
  - jekyll-assets
assets:
  prefix: "/assets"
